### ISSUE TITLE
Doesn't compile. (Gentoo Linux)

### ISSUE THREAD

**Issue by Oglo12** [nic-hartley/redshell#8]
I haven't tested this on other machines, but here on my Gentoo Linux machine it fails to compile.

![image](https://github.com/nic-hartley/redshell/assets/80219532/233771ae-d624-4a70-8272-4d9a22b495b4)

**Comment by nic-hartley** [comment]
Not gonna lie, I'm astonished anyone tried compiling it. I haven't had the time or inclination to touch this or [its engine](https://github.com/nic-hartley/tuig) in a hot minute.

This is a case of the bad error messages: You need to add at least one platform feature. I recommend `plat_steam` (the graphical option, currently quite poorly named as there's no steam support). `plat_ssh` also works, but can't currently be exited.

Nice console theme, by the way!
